### PR TITLE
Add talks from Deno Warsaw

### PR DESCRIPTION
**Pull request by bartlomieju**

### CODE REVIEW

**Comment by zekth** [comment]
Seems like slides from rafal point to a link that is already in the readme which detects dupes. Is it possible to fix?

**Comment by kevinkassimo** [comment]
@zekth it is not dup. This link https://pocztarski.com/wid/wid 404s.
The other deno.land/x/ failure is strange and has been failing ever since the new website...

**Comment by bartlomieju** [comment]
> @zekth it is not dup. This link https://pocztarski.com/wid/wid 404s.
> The other deno.land/x/ failure is strange and has been failing ever since the new website...

I fixed that, but that link is a redirect :sad:

**Comment by zekth** [comment]
> > @zekth it is not dup. This link https://pocztarski.com/wid/wid 404s.
> > The other deno.land/x/ failure is strange and has been failing ever since the new website...
> 
> I fixed that, but that link is a redirect :sad:

try using the redirected uri? https://gitpitch.com/rsp/wid/wid ?

**Comment by bartlomieju** [comment]
> > > @zekth it is not dup. This link https://pocztarski.com/wid/wid 404s.
> > > The other deno.land/x/ failure is strange and has been failing ever since the new website...
> > 
> > 
> > I fixed that, but that link is a redirect :sad:
> 
> try using the redirected uri? https://gitpitch.com/rsp/wid/wid ?

Did that, the issue with standard lib persist as described by @kevinkassimo

**Pull request merged**
