### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ralyodio**
add primatejs and fastest.engineer

### CODE REVIEW

**Comment by kt3k** [comment]
Is fastest.engineer open source?

Does primate have any Deno specific feature?

**Comment by ralyodio** [comment]
fastest.engineer is not open source. primate however works with node, bun and deno

**Comment by kt3k** [comment]
We don't include non open source material as showcase entry

**Comment by ralyodio** [comment]
i removed fastest.engineer

**Review by kt3k — APPROVED** [review]
LGTM

**Pull request merged**
