### PR TITLE
Categorize modules

### PR DESCRIPTION
**Pull request by kt3k**
This PR categorize modules into the following 17 categories:

- Automation
- CLI utils
- Frontend framework
- Frontend development
- Database
- Logging
- Mail
- Markdown
- String utils
- Template engine
- Testing
- Web framework
- WebSocket
- Webview
- Web utils
- XML
- Utils

### CODE REVIEW

**Review by zekth — COMMENTED** [review]
Wouldn't it be better to order modules alphabetically?

**Comment by kt3k** [comment]
Other awesome lists for languages/engines do this sort of categorization
- node.js https://github.com/sindresorhus/awesome-nodejs
- python https://github.com/vinta/awesome-python
- go https://github.com/avelino/awesome-go
- rust https://github.com/rust-unofficial/awesome-rust

I think this would be better for discoverability of libraries. If a user visits this list with some specific purpose, they can quickly jump to relevant categories and find what they look for.

**Comment by zekth** [comment]
@kt3k i was meaning the order of categories : https://github.com/denolib/awesome-deno/pull/270/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R16-R32

**Review by zekth — APPROVED** [review]
lgtm

**Pull request merged**
