### PR TITLE
added translated website

### PR DESCRIPTION
**Pull request by genemators**
There exists a lot of people who can't understand English even if it's internation language. We took the original website and translated it to uzbek and credited to original site with author. Thanks for your attention)

### CODE REVIEW

**Comment by FranciscoImanolSuarez** [comment]
Wow, did the translation cost you a lot?

**Comment by genemators** [comment]
> Wow, did the translation cost you a lot?

Nah, actually a few people from my local country asked me for it and did it. I'd be very thankful if you permit us to add our translated website)

**Comment by genemators** [comment]
> I sent a request for approval, unfortunately I don't know that language to qualify the translation, and unfortunately I don't manage this repository.

**Bro, If you want I can give you contribution permission, so you can manage my repo) I'll be glad for it.**

**Comment by genemators** [comment]
> I sent a request for approval, unfortunately I don't know that language to qualify the translation, and unfortunately I don't manage this repository.

If you want, I can give you permission to my repo, so you can edit or whatever)

**Pull request merged**
