### PR TITLE
Added denon tool and module

### PR DESCRIPTION
**Pull request by eliassjogreen**
Repository: https://github.com/eliassjogreen/denon/

Added both to tools and modules due to it also exporting a file watcher generator.

### CODE REVIEW

**Comment by hashrock** [comment]
Great library!

I Got CI error: 

```
Issues :-(
> Links 
  All OK ✓
> Dupes 
  1. [L54] https://github.com/eliassjogreen/denon
```

This is a limitation of awesome-bot, Could you remove either link?

**Comment by hashrock** [comment]
or should we use `--allow-dupe` for this purpose?

@kevinkassimo Can I get your opinion?

**Comment by kt3k** [comment]
How about making the watcher linked to [this file](https://github.com/eliassjogreen/denon/blob/master/watcher.ts) directly?

**Comment by eliassjogreen** [comment]
Just changed the denon watcher link to the watcher file

**Pull request merged**
