### PR TITLE
added Marked

### PR DESCRIPTION
**Pull request by dym-sh**

### CODE REVIEW

**Comment by zekth** [comment]
@kevinkassimo this port can adresses the concern of deno_std server to render markdown files

**Comment by kevinkassimo** [comment]
@dym-sh Yeah but then it needs to be part of deno_std. I am for this, but we need to confirm with both @ry and @styfle to see if this is okay.

**Comment by styfle** [comment]
Today, marked isn't written in typescript. Is that going to be a problem?

**Comment by kevinkassimo** [comment]
@styfle I don't think it would be a huge issue, as long as the interface is marked with types we can gradually bring types in for internal details. We did the same thing with prettier.

**Pull request merged**
